services:
  memcached:
    image: memcached
    container_name: '${APP_NAME:-unisurf}_memcached'
    hostname: memcached
    restart: unless-stopped
    environment:
      MEMCACHED_MEMORY_LIMIT: 128
    networks:
      - internal

networks:
  internal:
