services:
  phpmyadmin:
    #image: phpmyadmin/phpmyadmin
    image: arm64v8/phpmyadmin
    container_name: '${APP_NAME:-unisurf}_phpmyadmin'
    hostname: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-nopassword}'
    depends_on:
      - database
    ports:
      - '${PHPMYADMIN_PORT:-8092}:80'
    networks:
      - internal
      - external
